version: '3'

services:
  neo4j:
    image: neo4j:4.4.2
    container_name: graph_neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/admin
      - NEO4J_dbms_memory_transaction_global__max__size=4g
      - NEO4J_dbms_memory_heap_initial__size=4g
      - NEO4J_dbms_memory_heap_max__size=4g
      - NEO4J_dbms_memory_pagecache_size=4g
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
